#!/usr/bin/env bash

# $1 (optional): install location. Defaults to ~/Applications on Mac, ~/bin on other *n*x.
# $2 (optional): user-writable man pages directory. Defaults to the first element if any
#    of $MANPATH which is a subdir of $HOME (actually, to the man1 subdirectory of that
#    directory), otherwise ~/man/man1.

CHANGELOG_DIR="${TMP:-${TEMP:-${TMPDIR:-/tmp}}}"

# Keep git-merge from going all interactive in git >= 1.7.10
MERGE_AUTO_EDIT=no

#!!! BASHISM !!! OSTYPE not in dash (?)
if [ "x${OSTYPE}x" = "xdarwinx" ]; then
    SRC_DIR="${1:-${HOME}/Applications}"
    IS_MAC='true'
    ECHO='echo -e'
else
    SRC_DIR="${1:-${HOME}/bin}"
    IS_MAC=
    ECHO='/bin/echo -e'
fi

export no_proxy="git.infradead.org,github.com${no_proxy:+,}${no_proxy}"

INSTALL_DIR="${SRC_DIR}/get_iplayer"

if [ -d "$INSTALL_DIR" ] ; then
    cd "$INSTALL_DIR" &> /dev/null || exit 1

    $ECHO "Fetching...\n" 1>&2

    # Update
    git fetch | "$PAGER"

    $ECHO "\nChanges:\n" 1>&2

    # Check changes
    CHANGELOG="${CHANGELOG_DIR}/u-g-i-git-log"
    git log HEAD..origin > "$CHANGELOG"
    if [ ! -s "$CHANGELOG" ]; then
        echo "None." 1>&2
        exit 0
    fi
    "$PAGER" "$CHANGELOG"

    echo 1>&2
    read -p "Press Enter to proceed..." 1>&2
    echo 1>&2

    # Merge
    git merge origin

    echo 1>&2

    echo "Updated get_iplayer to git HEAD." 1>&2
else
    cd "$SRC_DIR" &> /dev/null || exit 2
    git clone 'https://github.com/get-iplayer/get_iplayer.git'
    cd "$INSTALL_DIR" &> /dev/null || exit 3
fi

# assert: We are in $INSTALL_DIR

# Don't use grep's --max-count switch, for OpenBSD compatibility, use head instead
MAN_DIR_ROOT="${2:-`manpath|tr ':' '\n'|grep "$HOME"|head -1`}"
MAN_DIR="${MAN_DIR_ROOT:-${HOME}/man}/man1"

echo -n "Installing manpage..."
mkdir -p "$MAN_DIR" || exit 4
cp -f get_iplayer.1 "$MAN_DIR"
cd "$MAN_DIR"
ln -sf get_iplayer.1 get-iplayer.1

read -p "Press Enter to exit..."
echo 1>&2
